name: Add tag of squad to each PR

on:
  pull_request:

jobs:
  label:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

    - if: ${{ contains('@dvbtrung2302', ${{ github.event.pull_request.user.login }}) }}
            name: Squad User Labeling
            uses: actions-ecosystem/action-add-labels@v1
            with:
              labels: |
                Squad User